# Generated by Django 6.0.6 on 2026-06-30 19:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('task_created', 'task_created'), ('task_moved', 'task_moved'), ('task_assigned', 'task_assigned'), ('task_deleted', 'task_deleted'), ('member_invited', 'member_invited'), ('member_removed', 'member_removed'), ('comment_added', 'comment_added')], db_column='eventType', max_length=30)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
    ]
